/* Executed in real Edge by tests/browser-check.ps1. */
(async () => {
 const get=id=>document.getElementById(id), checks=[];
 const check=(name,ok)=>{if(!ok)throw Error(name);checks.push(name);};
 const wait=()=>new Promise(r=>setTimeout(r,100));
 const base=v=>{get('aircraftWeight').value=String(v);get('aircraftWeight').dispatchEvent(new Event('input',{bubbles:true}));};
 async function pick(key,value,confirm=true){
  get(key+'-trigger').click();
  const i=AutorotationInputs.fields[key].options.indexOf(value);
  check('Available selection '+key+'/'+value,i>=0);
  get('value-wheel').children[i].click();await wait();
  if(confirm)get('confirm-wheel').click();
 }
 check('Initial blank basic and total 450',get('aircraftWeight').value===''&&get('weight-preview').textContent==='450');
 check('Initial crew kg',get('crewKg').textContent==='（136.1 kg）');
 check('Initial values',get('crewWeight-value').textContent==='300'&&get('otherWeight-value').textContent==='0'&&get('oat-value').textContent==='20'&&get('fuelWeight-value').textContent==='150'&&get('pressureAltitude-value').textContent==='2,000');
 check('Input before results',get('preset-heading').getBoundingClientRect().top<get('result-heading').getBoundingClientRect().top);
 check('Chart display removed',!document.querySelector('img,.chart-panel,#chart-dot')&&!globalThis.AutorotationChartView);
 check('All inputs and total in first 844px',get('weight-preview').getBoundingClientRect().bottom<844);
 base(1600);check('Basic draft preview',get('weight-preview').textContent==='2,050'&&get('aircraftWeight-state').textContent==='未確定');
 get('confirm-base').click();check('Basic confirmed',get('aircraftWeight-state').textContent==='確定済');
 base(1610);check('Basic reeditable',get('aircraftWeight-state').textContent==='未確定');base(1600);
 await pick('crewWeight',320,false);
 check('Live crew kg in modal',get('wheel-selection-value').textContent==='320 lb（145.1 kg）'&&get('crewKg').textContent==='（145.1 kg）');
 check('Wheel draft included before confirm',get('weight-preview').textContent==='2,070'&&get('wheel-total').textContent==='2,070');
 get('cancel-wheel').click();check('Cancel restores previous value',get('weight-preview').textContent==='2,050'&&get('crewWeight-value').textContent==='300');
 await pick('crewWeight',320);check('Wheel confirmed',get('crewWeight-state').textContent==='確定済'&&get('crewKg').textContent==='（145.1 kg）');
 await pick('crewWeight',340,false);get('cancel-wheel').click();
 check('Cancel restores confirmed status',get('crewWeight-state').textContent==='確定済'&&get('crewWeight-value').textContent==='320');
 await pick('otherWeight',50);check('Other added',get('weight-preview').textContent==='2,120');
 await pick('crewWeight',300);await pick('otherWeight',0);
 get('crewWeight-trigger').click();get('value-wheel').scrollTop=0;await wait();
 check('Scroll updates kg at crew minimum',get('wheel-selection-value').textContent==='250 lb（113.4 kg）'&&get('crewKg').textContent==='（113.4 kg）');
 get('cancel-wheel').click();
 get('oat-trigger').click();get('value-wheel').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));await wait();
 check('Keyboard wheel selection',get('oat-value').textContent==='21');
 get('wheel-dialog').dispatchEvent(new Event('cancel',{cancelable:true}));
 check('Escape cancels and restores focus',!get('wheel-dialog').open&&get('oat-value').textContent==='20'&&document.activeElement===get('oat-trigger'));
 get('fuelWeight-trigger').click();get('value-wheel').scrollTop=20*52;await wait();
 check('Scroll selection preview',get('fuelWeight-value').textContent==='200'&&get('weight-preview').textContent==='2,100');
 get('cancel-wheel').click();
 await pick('pressureAltitude',1000);await pick('oat',5);base(2058);
 const point={grossWeightLb:2508,densityAltitudeFt:AutorotationCalculator.densityAltitude(1000,5)};
 const expected=AutorotationCalculator.rotorSpeed(point,AutorotationChart);
 const fmt=v=>new Intl.NumberFormat('ja-JP',{maximumFractionDigits:1}).format(v);
 check('Above385 still shows RPM range',expected.referenceRpm>385&&get('referenceRpm').textContent===fmt(expected.referenceRpm)&&get('rpmRange').textContent===fmt(expected.minRpm)+' ～ '+fmt(expected.maxRpm)&&get('boundary-status').textContent==='385 RPM MAXIMUM超過');
 base(1450);check('Below series keeps warning',get('referenceRpm').textContent==='—'&&get('boundary-status').textContent==='332 RPM MINIMUM未満');
 const original=globalThis.AutorotationChart;
 globalThis.AutorotationChart={lookup:()=>({status:'ok',referenceRpm:330}),checkBoundaries:original.checkBoundaries};
 base(1450);check('Future below332 value remains visible',get('referenceRpm').textContent==='330'&&get('rpmRange').textContent==='325 ～ 335');
 globalThis.AutorotationChart=original;
 base(2200);check('Outside range clears RPM',get('referenceRpm').textContent==='—');
 base(1600);await pick('pressureAltitude',2000);await pick('oat',40);check('Outside altitude clears RPM',get('referenceRpm').textContent==='—');
 base(-1);check('Invalid basic clears stale RPM',get('referenceRpm').textContent==='—'&&get('boundary-status').textContent==='入力待ち'&&get('aircraftWeight').getAttribute('aria-invalid')==='true');
 check('Original notice preserved',document.querySelector('.data-note').textContent.includes('チャート画像からの暫定デジタイズ値・原典確認前'));
 get('reset-inputs').click();check('Reset returns all defaults',get('weight-preview').textContent==='450'&&get('oat-value').textContent==='20'&&get('pressureAltitude-value').textContent==='2,000');
 base(1600);get('confirm-base').click();
 check('No horizontal overflow',document.documentElement.scrollWidth<=innerWidth);
 window.scrollTo(0,0);await wait();
 return {passed:checks.length,checks};
})()
